databases:
  profiles:
    type: SQLite
    ip: ""
    port: ""
    database: "database"
    username: ""
    password: ""
sync:
  enabled: false
  ip: localhost
  port: 8080
  protection-key: "YOUR-PROTECTION-KEY"
  server-id: smp1